/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;
import java.util.List;
import model.Cliente;
import model.Encomenda;

/**
 *
 * @author jhona
 */
public class GuiPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form GuiPrincipal
     */
    
    private List<Cliente> clientes = new ArrayList();
    private List<Encomenda> encomendasAndamento = new ArrayList();
    private List<Encomenda> encomendasFinalizadas = new ArrayList();
    
    public GuiPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuCliente = new javax.swing.JMenu();
        gerenciarCliente = new javax.swing.JMenuItem();
        encomendaMenu = new javax.swing.JMenu();
        gerenciarEncomenda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestão de Encomendas");
        setAutoRequestFocus(false);
        setPreferredSize(new java.awt.Dimension(400, 300));
        setSize(new java.awt.Dimension(400, 300));

        menuCliente.setMnemonic('f');
        menuCliente.setText("Cliente");
        menuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClienteActionPerformed(evt);
            }
        });

        gerenciarCliente.setText("Gerenciar");
        gerenciarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciarClienteActionPerformed(evt);
            }
        });
        menuCliente.add(gerenciarCliente);

        menuBar.add(menuCliente);

        encomendaMenu.setMnemonic('e');
        encomendaMenu.setText("Encomenda");

        gerenciarEncomenda.setText("Gerenciar");
        gerenciarEncomenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciarEncomendaActionPerformed(evt);
            }
        });
        encomendaMenu.add(gerenciarEncomenda);

        menuBar.add(encomendaMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClienteActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuClienteActionPerformed

    private void gerenciarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciarClienteActionPerformed
        // TODO add your handling code here:
        GuiGerenciarClientes gi = GuiGerenciarClientes.getInstance();
        if (gi==null) return;
        gi.setClientes(clientes); //set list of clients
        desktopPane.add(gi);
        gi.setVisible(true);
        clientes = gi.getClientes(); //get new list of clients
    }//GEN-LAST:event_gerenciarClienteActionPerformed

    private void gerenciarEncomendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciarEncomendaActionPerformed
        // TODO add your handling code here:
        GuiGerenciarEncomendas gi = GuiGerenciarEncomendas.getInstance();
        if(gi==null) return;
        gi.setEncomendasAndamento(encomendasAndamento);
        gi.setEncomendasFinalizadas(encomendasFinalizadas);
        gi.setClientes(clientes);
        desktopPane.add(gi);
        gi.setVisible(true);
        encomendasAndamento = gi.getEncomendasAndamento();
        encomendasFinalizadas = gi.getEncomendasFinalizadas();
    }//GEN-LAST:event_gerenciarEncomendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiPrincipal().setVisible(true);
            }
        });
    }

    public List<Cliente> getClientes() {
        return clientes;
    }

    public void setClientes(List<Cliente> clientes) {
        this.clientes = clientes;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu encomendaMenu;
    private javax.swing.JMenuItem gerenciarCliente;
    private javax.swing.JMenuItem gerenciarEncomenda;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCliente;
    // End of variables declaration//GEN-END:variables

}
